### ISSUE TITLE
[Bug report] Might be an error in ZCR with StyleGAN

### ISSUE THREAD

**Issue by sunkicheon** [POSTECH-CVLab/PyTorch-StudioGAN#110]
https://github.com/POSTECH-CVLab/PyTorch-StudioGAN/blob/55576f2e2f99dd78069d1a47d2963daf7f4502d0/src/utils/sample.py#L151-L158
In this line, the "fake_images" variable should be "_, fake_images_eps", is that correct?

**Comment by MINGUKKANG** [comment]
Hi!

Thank you for your bug reporting. 

You are right and I will fix the bug ASAP.

Best,

Minguk
