### ISSUE TITLE
Add SupCon loss and nt-xent loss for comparison

### ISSUE THREAD

**Issue by 3288103265** [POSTECH-CVLab/PyTorch-StudioGAN#115]
Hi, thanks for your contribution. It seems that the 2C loss is a kind of supervised contrastive loss, so the [SupCon](https://arxiv.org/abs/2004.11362) should be a supervised baseline. Besides, it seems that the NT-Xent loss is removed, which is an unsupervised baseline. So, could you please add the SupCon loss and the Nt-Xent loss for comparison?

**Comment by MINGUKKANG** [comment]
2C loss and D2D-CE loss are similar to SupCon loss, but they are different as 2C, and D2D-CE losses do not require additional augmentations to make a positive sample. 

I tried XT-Xent and SupCon losses for image generation, and the synthesis results on ImageNet are not good (FID values are over 100). 

So, we decided to remove XT-Xent and SupCon losses from StudioGAN library.

Thank you.

Best,

Minguk
