### ISSUE TITLE
No `args.eval`

### ISSUE THREAD

**Issue by swyoon** [POSTECH-CVLab/PyTorch-StudioGAN#118]
Thank you very much for your amazing repo.

I found that there is no `eval` attribute in the command line arguments.

I was running the following command:
```
CUDA_VISIBLE_DEVICES=0,1 python3 src/main.py -s -cfg src/configs/CIFAR10/StyleGAN2.yaml -ckpt ckpt -save samples/
```
Line 103 of main.py checks for `args.eval` but it seems that there is no such argument.

https://github.com/POSTECH-CVLab/PyTorch-StudioGAN/blob/8a4d45923cabc383898bd8e4476246a465227e6d/src/main.py#L103

If I delete the check for `args.eval`, then I encounter another error.
```
Traceback (most recent call last):
  File "src/main.py", line 154, in <module>
    cfgs, gpus_per_node, run_name, hdf5_path, rank = load_configs_initialize_training()
  File "src/main.py", line 121, in load_configs_initialize_training
    cfgs.check_compatability()
  File "/opt/home3/swyoon/PyTorch-StudioGAN/src/config.py", line 620, in check_compatability
    if not self.RUN.train and self.RUN.eval:
AttributeError: 'make_empty_object' object has no attribute 'eval'
```

**Comment by MINGUKKANG** [comment]
I will fix the bug tomorrow (with the implementation of clean-FID).

Thank you.

Best,

Minguk

**Comment by MINGUKKANG** [comment]
Sorry for the late reply.

I removed the unnecessary eval argument that seems to be caused by the recent update for convenient evaluation.

Would you please pull StudioGAN and try the command again?

Thank you.

**Comment by swyoon** [comment]
Thank you so much for your effort, and also sorry for the late reply.

I finally end up with the following command :
```
CUDA_VISIBLE_DEVICES=0,1 python3 src/main.py -s -cfg src/configs/CIFAR10/StyleGAN2.yaml -ckpt ckpt -save samples/ --data data -best
```

Thank you.
