### ISSUE TITLE
A circular import in utils/misc.py

### ISSUE THREAD

**Issue by vis-opt-group** [POSTECH-CVLab/PyTorch-StudioGAN#119]
I encountered this problem when running the following command

> python ./src/main.py -t -metrics is fid prdc -cfg ./src/configs/CIFAR10/LGAN.yaml -data ./data/ -save ./result/

> Traceback (most recent call last):
>   File "/root/gan/PyTorch-StudioGAN-master/src/main.py", line 19, in <module>
>     import config
>   File "/root/gan/PyTorch-StudioGAN-master/src/config.py", line 16, in <module>
>     import utils.misc as misc
>   File "/root/gan/PyTorch-StudioGAN-master/src/utils/misc.py", line 33, in <module>
>     import utils.sample as sample
>   File "/root/gan/PyTorch-StudioGAN-master/src/utils/sample.py", line 21, in <module>
>     import utils.losses as losses
>   File "/root/gan/PyTorch-StudioGAN-master/src/utils/losses.py", line 36, in <module>
>     import utils.misc as misc
> AttributeError: module 'utils' has no attribute 'misc'

**Comment by MINGUKKANG** [comment]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/30516904/147410340-29f1084e-8d8c-4f7a-8078-07b94c0abc15.png">


In my case, the command you provide works well. 

Could you please give me more information about your environment and execution specification?

Thank you.

**Comment by lizaitang** [comment]
I think it is a circular imports problem for utils, please solve it.

**Comment by MINGUKKANG** [comment]
Could you please pull the repository and check it again?

**Comment by Muaz65** [comment]
is there any update on this? I am still getting this issue

`Traceback (most recent call last):
  File "./src/main.py", line 19, in <module>
    import config
  File "/home/omnoai/Desktop/Muaz/PyTorch-StudioGAN/src/config.py", line 16, in <module>
    import utils.misc as misc
ModuleNotFoundError: No module named 'utils.misc'
`

**Comment by MINGUKKANG** [comment]
could you give me the details of your environment including os, python, torch version?

**Comment by Muaz65** [comment]
I am using ubuntu 18.06 with following versions 
torch                        1.10.1                 
torchaudio               0.4.0               
torchsummary         1.5.1              
torchvision               0.11.2           
python                     3.6.12

**Comment by MINGUKKANG** [comment]
Thank you a lot! I will update PyTorch-StudioGAN ASAP.

**Comment by Muaz65** [comment]
Thankyou for swift response. I also tried different tags and log branch. The issue persists. I have tried all possible combination with and without terminal args. 

`python3 src/main.py -t -metrics is fid prdc -cfg ./configs/CIFAR10/LGAN.yaml -data ./data/ -save ./results/`

**Comment by alex4727** [comment]
Well from the above command, it seems like you put the wrong cfg path. (should probably be src/configs/CIFAR10/LGAN.yaml) Could you try again with proper cfg path?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Muaz65** [comment]
I copied the wrong command (have fixed it now). I am using the correct path and the issue persists

**Comment by Muaz65** [comment]
I have fixed the error by adding following code:  
`import sys`
`sys.path.append("./src/utils")`

- src/config.py
- src/utils/ckpt.py
- src/utils/losses.py
- src/utils/sample.py
- src/utils/misc.py

But this is just a temporary fix.

**Comment by MINGUKKANG** [comment]
I have found that the problem is a circular import problem that occurs when using python 3.6 version. 

I solved the problem, so please let me know if there still exists an import issue by pulling the main branch. 

Thank you. 

Minguk
