### ISSUE TITLE
Which dockerfile to use?

### ISSUE THREAD

**Issue by JihadFenix** [POSTECH-CVLab/PyTorch-StudioGAN#129]
Hi, 
I am having trouble making studio_gan docker work. 
Following the instructions in readme, I downloaded the mgkang/studio_gan:latest dockerfile (which is 83.6G after successfully pulled) and then made a container using the provided command:
`docker run -it --gpus all --shm-size 128g --name StudioGAN -v /home/USER:/root/code --workdir /root/code mgkang/studio_gan:latest /bin/bash`
However, in the container instance, I couldn't find viable pytorch installation,  or package managing tools like pip or conda:
![Screenshot from 2022-02-09 21-22-00](https://user-images.githubusercontent.com/13739682/153238612-6e5279ea-f7ea-4401-89f4-545046281090.png)
 
By searching on dockerhub, I could find another repository under mgkang, named studiogan. Should I be using this one instead?  
I am very impressed by your work. Any help will be greatly appreciated. Thanks.

**Comment by MINGUKKANG** [comment]
I am sorry. 

I forgot to update the docker file since I recently updated StudioGAN. 

mgkang/studio_gan is my own docker file thus, please try to use mgkang/studiogan instead.

Best,

Minguk

**Comment by JihadFenix** [comment]
Thank you for the quick reply! I pulled studiogan:latest and install additional dependencies. Now it works!!
Another issue though. I have a rtx3090 and a 1080ti. But the dockerfile has cuda v10.1 installed so when I try to run it on 3090, this error came up:

> RuntimeError: CUDA error: no kernel image is available for execution on the device

Have you tried running StudioGAN on the Ampere generation GPUs? Any plan on adapting to the newer hardware?

**Comment by MINGUKKANG** [comment]
To run StudioGAN on the Ampere generation GPUs (especially 3090), you must change the current coda version to coda 11.1 or higher.

After changing the coda version, I am sure StudioGAN will work well since I have some experience running StudioGAN on 3090 GPUs.

Thank you.

**Comment by JihadFenix** [comment]
Cool. Thank you for the reply! I'll try set it up.
