### ISSUE TITLE
if I want to check 【Adaptive Discriminator Augmentation】 How to set configs file？？

### ISSUE THREAD

**Issue by Johnson-yue** [POSTECH-CVLab/PyTorch-StudioGAN#13]
maybe：
“ada” ：true，
“ada_target" :  ??
"ada_length" :  ???

as your code self.ada_aug_step = self.ada_target / self.ada_length   , Would you give a reference value ??

**Comment by MINGUKKANG** [comment]
Hi:)

if you use the hinge losses for the generator and discriminator, ada_target = 0.2, ada_length = 1,000,000, and total step = 150,000 might give you comparable results with the original paper (not identified yet). However, I can't found the exact settings used in the paper, we should search for a proper hyperparameter setting to reproduce numbers in the paper :(

Sincerely, 

Minguk Kang

**Comment by Johnson-yue** [comment]
The code has been updated frequently recently (thank you for your work, I will continue to pay attention to it), so I may have to wait until the code is stable before testing, or you can give a set of recommended parameters after testing。

I will keep this issue open ， If you feel the code is stable，then close it

**Comment by syncle** [comment]
@MINGUKKANG Is this a pending issue?

**Comment by MINGUKKANG** [comment]
@syncle @Johnson-yue  StudioGAN's code has been stabilized.
