### ISSUE TITLE
What should std_max and std_step be set to reproduce the results?

### ISSUE THREAD

**Issue by houliangict** [POSTECH-CVLab/PyTorch-StudioGAN#134]
Hi,

Thank you for your great work in the GAN field. I would like to know what should std_max and std_step be set to reproduce the results in the ImageNet experiment of the ReACGAN paper.

**Comment by MINGUKKANG** [comment]
--std_max 512 --std_step 512 will reproduce the result in ReACGAN paper. 

Thank you.

**Comment by houliangict** [comment]
Thank you for your prompt reply. Is this because the batchsize is 512? If the batchsize is 256, should they be 256?

**Comment by MINGUKKANG** [comment]
Yes, that is my heuristics.

**Comment by houliangict** [comment]
If I understand correctly, --std_max 512 --std_step 512 is the setting for ImageNet 2048 B.S. while std_max and std_step for ImageNet 256 B.S. should be 256. Please correct me if I'm wrong.

**Comment by MINGUKKANG** [comment]
You are right:)

**Comment by MINGUKKANG** [comment]
@houliangict 

Hello,

I recently changed the pre-processing resizer defined in data_util.py from PIL.BILINEAR to PIL.LANCZOS.

And, I found that the modification can lead wrong comparisons between the current and prevision models. 

Please change the below source code:

```python
# in src/data_util.py
if self.hdf5_path is None:
    if crop_long_edge:
        self.trsf_list += [CenterCropLongEdge()]
    if resize_size is not None:
        self.trsf_list += [transforms.Resize(resize_size, Image.LANCZOS)]
else:
    self.trsf_list += [transforms.ToPILImage()]
```

to

```python
# in src/data_util.py
if self.hdf5_path is None:
    if crop_long_edge:
        self.trsf_list += [CenterCropLongEdge()]
    if resize_size is not None:
        self.trsf_list += [transforms.Resize(resize_size, Image.LANCZOS)]
else:
    self.trsf_list += [transforms.ToPILImage()]
```

, if you want to reproduce previous results reported in our ReACGAN paper.

Thank you.

Best,

Minguk

**Comment by houliangict** [comment]
Thank you for your reminder. This is very helpful to me. I wonder what effect this pre-processing change will have on the results. Will it make the FID/IS worse or better?

**Comment by MINGUKKANG** [comment]
Now we prepare a paper regarding the importance of choosing a pre-precessing resizer with large-scale evaluation tables. 

The paper will be open to the public within a month. 

Thank you.

Best,

Minguk
