### ISSUE TITLE
How to generate images

### ISSUE THREAD

**Issue by Derekabc** [POSTECH-CVLab/PyTorch-StudioGAN#164]
Hi all, could you please let me know what is the command to generate images with the trained models? I trained several approaches, but none of them work. I always face the issue:

![image](https://user-images.githubusercontent.com/25771207/186050051-440c6298-e8c6-4726-a493-075f7b8a9954.png)

**Comment by MINGUKKANG** [comment]
hi,

Can you try again after pulling the master branch?

**Comment by Derekabc** [comment]
hi, thanks for your reply! I am able to generate images by giving the dir for the training dataset.
