### ISSUE TITLE
Stuck after 'Setting up PyTorch plugin "bias_act_plugin"'

### ISSUE THREAD

**Issue by festinais** [POSTECH-CVLab/PyTorch-StudioGAN#166]
Hi, I'm trying to train **StyleGAN2-D2DCE-ADA.yaml** . All of a sudden it got stuck at this step:  'Setting up PyTorch plugin "bias_act_plugin"', as you can see in the screenshot:

<img width="752" alt="Screenshot 2022-08-25 at 14 43 45" src="https://user-images.githubusercontent.com/12886033/186711780-0ec6af3a-479a-4ea2-9630-a7481811efcf.png">

I left for almost an hour and it was stuck there. Any ideas why this might happen?

This is the command I'm using to train:
`CUDA_VISIBLE_DEVICES=0,1  python3 src/main.py -cfg src/configs/CIFAR10/StyleGAN2-D2DCE-ADA.yaml -t -metrics fid -save stylegan_curated_overlap_d2d_ada -data data/CUSTOM -ref "test" -mpc`

torch version: 1.13.0.dev20220825+cu116
cuda: 11.6
Also, pulled the latest updates.

**Comment by MINGUKKANG** [comment]
Please execute following commands:

>> export LIBRARY_PATH=/opt/conda/lib/

>> conda deactivate

>> conda activate

if it does not work, I suggest removing PyTorch 1.13.0.dev20220825+cu116 and reinstalling PyTorch 1.12 with cu113.

Thanks.

**Comment by festinais** [comment]
Thank you for your quick answer! Which python version do you recommend also?

**Comment by festinais** [comment]
It works now. I have CUDA 11.6, python 3.9, and torch 1.12+cu116

For CUDA 11.6 there is only torch with version 1.12. This is how I installed torch: `pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
`
You can take a look more at this link `https://download.pytorch.org/whl/cu116`. 

Also, I had many problems with upfirdn2d_plugin and bias_act_plugin plugins, till I made it work. What helped me was:

1. Create a new venv with conda
2. Make sure to clean everything with: `pip freeze | xargs pip uninstall -y`
3. Also, make sure to clean pip cache with: `pip cache purge`
4. Check inside this link `https://download.pytorch.org/whl/torch/` for the torch that is compatible with your CUDA version. For example `torch-1.12.0+cu116-cp310-cp310-linux_x86_64.whl` is compatible with CUDA 11.6 and python 3.10. 

These steps help me solve the **bias_act_plugin** and **upfirdn2d_plugin** problems.
