### ISSUE TITLE
Cannot load biggan for cifar10

### ISSUE THREAD

**Issue by flymin** [POSTECH-CVLab/PyTorch-StudioGAN#168]
Hi,

I fail to load the pretrain weight located "Pre-trained_weights/CIFAR10/BigGAN-Deep-train-2020_09_17_13_44_46". I tried with both "src/configs/CIFAR10/BigGAN-Deep-StudioGAN.yaml" and "src/configs/CIFAR10/BigGAN-Deep.yaml". Neither of them seem to work.

And the folder "Pre-trained_weights/CIFAR10/BigGAN-train-2021_01_15_14_48_48" seems do not contrain pretrained weights.

Could please you fix this and provide a usable biggan model on cifar10?

Thanks.

**Comment by MINGUKKANG** [comment]
Hi,

We deleted pretrained weights temporarily for internal reasons.

However, I can share some weights for only research purpose.

Can you tell me the GAN models  you want to use ? 

Sorry for the late reply.

**Comment by MINGUKKANG** [comment]
I will share the BIgGAN weight next day evening.

**Comment by flymin** [comment]
I just want to try biggan series on cifar10. Could you share the weights and configs?
You may send them through email to: rygao@cse.cuhk.edu.hk (if you cannot make them public)
I will only use them for research purposes. Thank you!

**Comment by MINGUKKANG** [comment]
Hello!

Here is the pertained BigGAN weight on CIFAR10 [Googledrive](https://drive.google.com/drive/folders/1s6sL3ov2VC1EO1aaHJFhegvCkEOMM2fZ?usp=sharing) and corresponding configuration [config](https://github.com/POSTECH-CVLab/PyTorch-StudioGAN/blob/master/src/configs/CIFAR10/BigGAN.yaml).

Good luck.

Best,

Minguk

**Comment by flymin** [comment]
Thank you for your help! I can use them now.
