### ISSUE TITLE
Why is config for `Tiny_ImageNet` removed ?

### ISSUE THREAD

**Issue by krenerd** [POSTECH-CVLab/PyTorch-StudioGAN#172]
In the current version of `master` branch(which is the only branch), config files for running experiments on Tiny ImageNet dataset don't exist. I remember that the configs were previously defined in `src/configs/Tiny_ImageNet` folder. 

I noticed that the folder was removed with the [commit](https://github.com/POSTECH-CVLab/PyTorch-StudioGAN/commit/394c9b06d1548d448001629f3496344bef90ccb9) on July 3, 2022. (Note: [before](https://github.com/POSTECH-CVLab/PyTorch-StudioGAN/tree/78ca786d7ed80b78ffd3d1aa6b25860861639fef/src/configs) and [after](https://github.com/POSTECH-CVLab/PyTorch-StudioGAN/tree/394c9b06d1548d448001629f3496344bef90ccb9/src/configs)).

The new dataset added in the update is very interesting, but is there a reason for removing Tiny_ImageNet? Considering that the code still works with previous configs perhaps the folder was accidentally removed?

Additionally, if the `Tiny_ImageNet` dataset is still supported, is it correct to download the dataset as follows for reproducing results? The `tiny-imagenet-200` folder consists of `[train, val, test]` subfolders and I'm not sure if using `tiny-imagenet-200/val` as validation is correct. 

```
!wget http://cs231n.stanford.edu/tiny-imagenet-200.zip

# process
!wget https://gist.github.com/moskomule/2e6a9a463f50447beca4e64ab4699ac4/raw -O process_tiny_imagenet.sh
!bash process_tiny_imagenet.sh

!mv tiny-imagenet-200/val tiny-imagenet-200/valid
```

I very much appreciate your work!

**Comment by alex4727** [comment]
Tiny ImageNet, as mentioned in our paper StudioGAN, contains a lot of degraded images so we haven’t used them for experiments in our paper (instead we made new ImageNet Variants Baby/Papa/Grandpa ImageNet). We removed them for consistency with the paper. But yes, old Tiny ImageNet still works for most configs. We'll discuss about putting them back in next update! 
Yes, preparing it seems fine. FYI, valid folder should contain 10,000 images.

**Comment by krenerd** [comment]
> Tiny ImageNet, as mentioned in our paper StudioGAN, contains a lot of degraded images so we haven’t used them for experiments in our paper (instead we made new ImageNet Variants Baby/Papa/Grandpa ImageNet). We removed them for consistency with the paper. But yes, old Tiny ImageNet still works for most configs. We'll discuss about putting them back in next update! Yes, preparing it seems fine. FYI, valid folder should contain 10,000 images.

Thanks for the reply. 

I think the dataset is still useful as some papers are benchmarked on the tiny ImageNet dataset. I personally mentioned the dataset as I would like to reproduce the results of some previous work using StudioGAN.

**Comment by MINGUKKANG** [comment]
Thank you alex for your kind explanation:)
