### ISSUE TITLE
Would you write a [sample.py]

### ISSUE THREAD

**Issue by Johnson-yue** [POSTECH-CVLab/PyTorch-StudioGAN#18]
Hi,  I use the main.py  trained a biggan32 network with cifar10 and tinyImageNet, and I want to  random generate some sample,   but this framework has many options.

Would you write a  sample.py  file for random generate some sample with checkpoints ??

**Comment by MINGUKKANG** [comment]
Hi.

```
python3 main.py -s -std_stat --standing_step STANDING_STEP -c CONFIG_PATH --checkpoint_folder CHECKPOINT_FOLDER --log_output_path LOG_OUTPUT_PATH
```

The above command will generate fake samples in "./generated_images".

Also, you can see generated images using tensorboard during training.

Sincerely, 

Minguk Kang

**Comment by Johnson-yue** [comment]
ok， I will try it

**Comment by syncle** [comment]
@MINGUKKANG Is this a pending issue?

**Comment by MINGUKKANG** [comment]
Hi.

CUDA_VISIBLE_DEVICES=0,1,... python3 main.py -iv -std_stat --standing_step STANDING_STEP -c CONFIG_PATH --checkpoint_folder CHECKPOINT_FOLDER --log_output_path LOG_OUTPUT_PATH

The above command will generate fake samples in "./figures/RUN_NAME/*.png."

Sincerely,

Minguk Kang

**Comment by Johnson-yue** [comment]
Thank you
