### ISSUE TITLE
how to use DCGAN weights?

### ISSUE THREAD

**Issue by coloedrainbow** [POSTECH-CVLab/PyTorch-StudioGAN#185]
I know that all checkpoints are aviable at Hugging Face Hub, and to train a model we use  `-t` falg like the following:
```
CUDA_VISIBLE_DEVICES=0 python3 src/main.py -t -metrics is fid prdc -cfg CONFIG_PATH -data DATA_PATH -save SAVE_PATH

```

But don'r know what's the falg for using weights that are saved in checkpoints.  can anyone give me an example of command for running DCGAN on one of the checkpoint using cifar10? 
I greatly apprecyiate any help! thanks!

**Comment by alex4727** [comment]
Hi, with checkpoint, you can use it with -ckpt flag to resume training. 
`CUDA_VISIBLE_DEVICES=0 python src/main.py -t -metrics is fid prdc -cfg CONFIG_PATH -data DATA_PATH -save SAVE_PATH -ckpt CKPT_FOLDER`

**Comment by coloedrainbow** [comment]
Hi @alex4727  thank you very much for the help!
Does that mean for runing with these checkpoint at [hugging_face](https://huggingface.co/Mingguksky/PyTorch-StudioGAN/tree/main/studiogan_official_ckpt/CIFAR10_tailored/CIFAR10-DCGAN-train-2022_01_11_20_32_07) I need to download them and put the folde path? It automatically knows which one is for Discriminator and which one is for Generator?

**Comment by alex4727** [comment]
Yes, all you have to do is download the specific folder that you are planning to use and make `-ckpt` flag point to that folder. Because checkpoints are saved with certain naming conventions, the files are loaded to the generator and the discriminator automatically.
One important option when resuming or sampling from pretrained models is `-best` flag. For every models, we save checkpoints for the best and the latest step. We recommend using `-best` flag for sampling purpose.

**Comment by coloedrainbow** [comment]
Thank you @alex4727 very much!

**Comment by coloedrainbow** [comment]
Sorry @alex4727  with such a basic question. But this does not work quite right. I've downloaded the [best checkpoints](https://huggingface.co/Mingguksky/PyTorch-StudioGAN/tree/main/studiogan_official_ckpt/CIFAR10_tailored/CIFAR10-DCGAN-train-2022_01_11_20_40_00) and upload it to colab, and ran 

```
!CUDA_VISIBLE_DEVICES=0 python3  \
/content/PyTorch-StudioGAN/src/main.py \
-t -metrics is fid prdc \
-cfg /content/PyTorch-StudioGAN/src/configs/CIFAR10/DCGAN-Info.yaml\
 -data data/cifar10 -save /content/results -ckpt /content/Checkpoints
```


There's a **RunTime Error**. what's the issue here?

```
  (activation): ReLU(inplace=True)
  (conv1): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (bn1): BatchNorm2d(512, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
  (linear1): Linear(in_features=512, out_features=1, bias=True)
  (info_discrete_linear): Linear(in_features=512, out_features=10, bias=False)
)
Traceback (most recent call last):
  File "/content/PyTorch-StudioGAN/src/main.py", line 192, in <module>
    loader.load_worker(local_rank=rank,
  File "/content/PyTorch-StudioGAN/src/loader.py", line 237, in load_worker
    ckpt.load_StudioGAN_ckpts(ckpt_dir=cfgs.RUN.ckpt_dir,
  File "/content/PyTorch-StudioGAN/src/utils/ckpt.py", line 85, in load_StudioGAN_ckpts
    prev_run_name = torch.load(Dis_ckpt_path, map_location=lambda storage, loc: storage)["run_name"]
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

![image](https://user-images.githubusercontent.com/105493301/232111912-2cbe0da4-a14d-43ac-b4ff-28897d614a7e.png)

**Comment by alex4727** [comment]
I see few problems.
1) Your checkpoint's matching config should be DCGAN.yaml not DCGAN-Info. 
2) If you do not specify with option `-best`, StudioGAN will resume from the last saved checkpoint which should be something including "....current-weights....". So if you are trying to resume from best step, make sure to put `-best` flag.
3) We only tested StudioGAN by running main.py from our root folder (python  src/main.py...). If you find problems related to importing modules, make sure you change the running directory using something like. 
`import os`
`os.chdir(...)`

**Comment by coloedrainbow** [comment]
Thank you again very much @alex4727.  I can put the `-best ` everywhere?  it's now runing but I thoght that with this command I can instantiate a DCGAN with the best weights, and then generate some images. My interprataion is wrong?
`!CUDA_VISIBLE_DEVICES=0 python3  \
/content/PyTorch-StudioGAN/src/main.py \
-t -metrics is fid prdc \
-cfg /content/PyTorch-StudioGAN/src/configs/CIFAR10/DCGAN.yaml\
 -data data/cifar10 -save /content/results -best -ckpt /content/Checkpoints`

**Comment by alex4727** [comment]
Can you be more specific on what you are trying to do? 
`-t` flag is about training so combined with `-ckpt` it is natural that you get a resumed training session. 
If you're just trying to generate few images look for `-sf` options. Please check our main.py for details on arguments.

**Comment by coloedrainbow** [comment]
@alex4727  Thanks for the information. Yes, I read your article and found that the FID is quite good for them. So, I'd like to use the exact same weight of differnt models and generate some images. I don't want to train it any further, just generate data for downstream tasks. So, could you please show me what command I can run to generate:
1- some images (like 100 images) by using best weight of DCGAN on cifar 10
2-  some images (like 100 images) by using best weight of DCGAN on a custom data set like (MyOwn_samll_data)
I also apologize for not knowing proper flags. I'm quite new to the filed as well as command line. Sorry about basic question. Thank you again for all the help and time.

**Comment by coloedrainbow** [comment]
can you give me some help, please. I'm confude by tags!   I just want to load available weights, generate some images, save them, and see the results (no traning)
```
Traceback (most recent call last):

  File "/content/PyTorch-StudioGAN/src/main.py", line 192, in <module>
    loader.load_worker(local_rank=rank,
  File "/content/PyTorch-StudioGAN/src/loader.py", line 237, in load_worker
    ckpt.load_StudioGAN_ckpts(ckpt_dir=cfgs.RUN.ckpt_dir,
  File "/content/PyTorch-StudioGAN/src/utils/ckpt.py", line 81, in load_StudioGAN_ckpts
    Gen_ckpt_path = glob.glob(glob.escape(x) + '*.pth')[0]
IndexError: list index out of range
```

![image](https://user-images.githubusercontent.com/105493301/232619531-8e2eb6c0-b744-4f74-b1d4-12a8c784cff8.png)

**Comment by alex4727** [comment]
Closing this issue, as it is being discussed in issue #189.
