### ISSUE TITLE
Building GAN with 96x96 images

### ISSUE THREAD

**Issue by MiguelCosta94** [POSTECH-CVLab/PyTorch-StudioGAN#198]
Is it possible to use this library to train a GAN for images with size 96x96? When I try to do this, I get the error:
```
File "/home/miguelcosta/Git/PyTorch-StudioGAN/src/models/big_resnet.py", line 73, in __init__
    self.in_dims = g_in_dims_collection[str(img_size)]
KeyError: '96'
```

**Comment by f-amerehi** [comment]
Hi @MiguelCosta94 If you want to train a GAN for images with a size of 96x96, you'll need to add key value entries for this specific image size (96 in your case)  in both  `g_in_dims_collection` and `g_out_dims_collection`  dictionaries at line [45](https://github.com/POSTECH-CVLab/PyTorch-StudioGAN/blob/master/src/models/big_resnet.py#L45)
