### ISSUE TITLE
Possibility of Loading various checkpoints during --eval_backbone for ResNet50_torch

### ISSUE THREAD

**Issue by f-amerehi** [POSTECH-CVLab/PyTorch-StudioGAN#203]
Hi,

I've trained ResNet50 in four different ways and saved checkpoints for each. I'm curious whether this repository supports the loading of custom checkpoints for ResNet50 when using `--eval_backbone ResNet50_torch`. If it does, could you tell on how to do so, please? Any advice would be appreciated.

Thanks

**Comment by mingukkang** [comment]
Regrettably, StudioGAN does not currently support this option. To enable it, you will need to make modifications.

**Comment by mingukkang** [comment]
please check [here](https://github.com/POSTECH-CVLab/PyTorch-StudioGAN/blob/master/src/metrics/preparation.py#L54-L59)

**Comment by f-amerehi** [comment]
Thanks a  lot @mingukkang  Have a nice day!
