### ISSUE TITLE
list out range bug 

### ISSUE THREAD

**Issue by Johnson-yue** [POSTECH-CVLab/PyTorch-StudioGAN#31]
Hi， Sorry, for my not elegant solution。

In  before pull requests,  it should be run the code in ROOTPATH

but , if some want run code in src/ path  maybe this is a better way to fixed :

original code :
https://github.com/POSTECH-CVLab/PyTorch-StudioGAN/blob/73a354d3ac6e911ef95e2bf6573578642b55e69d/src/loader.py#L52

new code  [in src/loader.py]:
`run_name = make_run_name(RUN_NAME_FORMAT, framework=cfgs.config_path.split('/')[-1][:-5], phase='train')`

And thank you for your quick response！！！

**Comment by MINGUKKANG** [comment]
Hi johnson:)

I modified the code you pointed out.

Thank you.

Sincerely,

**Comment by MINGUKKANG** [comment]
I will also
