### ISSUE TITLE
More configs and annotations

### ISSUE THREAD

**Issue by WingsleyLui** [POSTECH-CVLab/PyTorch-StudioGAN#32]
Neat work! 

Could you please 
1. give more annotations on each function/method/class, which may facilitate understanding the codes!
2. From your config files, I know how to run different type of GANs, but just to confirm, how to reproduce unconditional GAN? I thought two settings are related : `conditional strategy ` and `num_classes`. Can you give a detailed example such as unconditional SNGAN?

Thanks!

**Comment by MINGUKKANG** [comment]
Hi!

We plan to write a brief comment on functions/methods/classes (but not now):)

2. just change the configuration of src/configs/CIFAR10/SNGAN.json with "conditional strategy": "no" without change of num_classes. This will automatically build your model as the unconditional SNGAN.

In short, to train unconditional SNGAN on CIFAR10:
"num_classes": 10, 
"conditional_strategy": "no", 

Thank you.

**Comment by WingsleyLui** [comment]
@MINGUKKANG Thank you for your quick reply! Looking forward to your subsequent work 👍🏼
