### ISSUE TITLE
result is very bad

### ISSUE THREAD

**Issue by Johnson-yue** [POSTECH-CVLab/PyTorch-StudioGAN#5]
Hi，it‘s me again.

I see your update many code ,So I retrained the contraGAN with Cifar10 dataset ( as your ReadME first demo)again to check. but this result is very bad...  best FID = 250+

Ubuntu18.04 + pytorch 1.6.0 + torchvision 0.7.0 + CUDA 10.2 
the log file :
[contra_biggan_cifar32_hinge_no-train-2020_09_02_20_37_05.log](https://github.com/POSTECH-CVLab/PyTorch-StudioGAN/files/5165667/contra_biggan_cifar32_hinge_no-train-2020_09_02_20_37_05.log)

Sorry to bother you, but maybe should be check again?

**Comment by syncle** [comment]
Hi @Johnson-yue, I found some experimental codes are committed to the master branch. We have moved the experimental code to a separate branch, and we recovered stable code in the master branch.
@MINGUKKANG will confirm if the current master branch works fine.

**Comment by Johnson-yue** [comment]
Thank you very much for your work, I will always pay attention to it and contribute to it sometimes
please close this issue after comfirming it

**Comment by Johnson-yue** [comment]
@MINGUKKANG  This bug has been fixed？

**Comment by MINGUKKANG** [comment]
@Johnson-yue 

Hi.

Yes:) The bug is fixed. 

Now, we have refactorized our code for early version release. 

Thank you:)

MInguk Kang

**Comment by Johnson-yue** [comment]
ok, when you update , I will check again
