### ISSUE TITLE
Is it possible to run a demo without CUDA?

### ISSUE THREAD

**Issue by lihuiknight** [POSTECH-CVLab/PyTorch-StudioGAN#55]
FYI

**Comment by MINGUKKANG** [comment]
Hello,

Unfortunately, StudioGAN does not support a visualization demo that can be executed without CUDA. 

Best,  

Minguk Kang

**Comment by lihuiknight** [comment]
ok, thanks. the cpu version will benefit the local development and debug.
I close this issue.
