### ISSUE TITLE
RandomCropLongEdge

### ISSUE THREAD

**Issue by phymhan** [POSTECH-CVLab/PyTorch-StudioGAN#57]
Hi,

Thanks for releasing this great repo. I think in the custom function `RandomCropLongEdge()`, the last line should be
```
transforms.functional.crop(img, j, i, size[0], size[1])
```
or use its own `CenterCrop` in training, since PIL and torch has different definition of size. I'm using the latest version of torchvision (0.8.2) and pillow (7.0.0).

Thanks!

**Comment by MINGUKKANG** [comment]
Hello phymhan,

Thank to your reporting, I notice there is a critical bug in dataloader, especially, RandomCropLongEdge().

I have reflected the bug you mentioned.

Thank you very much. 

Best, 

Minguk

**Comment by phymhan** [comment]
Hi Minguk,

Thanks for your prompt reply! Just a quick question: Is there a way to resume interrupted training? Thanks a lot!

Best,
Ligong

**Comment by MINGUKKANG** [comment]
Hello:)

Absolutely, you can resume your training by typing the command below:

```
CUDA_VISIBLE_DEVICES=0,...,N python3 src/main.py -t -e -c CONFIG_PATH --checkpoint_folder CHECKPOINT_FOLDER --eval_type "valid"
```

Thank you.

**Comment by phymhan** [comment]
Got it. That's very clear. Thank you so much again!
