### ISSUE TITLE
does any document about upfirdn2d

### ISSUE THREAD

**Issue by lihuiknight** [POSTECH-CVLab/PyTorch-StudioGAN#60]
Dear author, 

I am running your code, does any document about `upfirdn2d`? What does upfirdn2d work for? 

Thanks

**Comment by MINGUKKANG** [comment]
Hello,

we borrowed upfirdn2d codes from https://github.com/rosinality/stylegan2-pytorch.

The upfirdn2d is used to conduct Adaptive Discriminator Augmentation (ADA) for limited data training. 

If you do not want to use ADA training, you can simply remove the codes and it will remove a compatibility issue regarding gcc library.

Please refer to the repo. above. 

Thank you.

**Comment by lihuiknight** [comment]
thanks, does any detailed explanation or tutorial for upfirdn2d?

**Comment by MINGUKKANG** [comment]
Sorry.

I don't know how upfirdn2d works in ADA exactly. 

Also, I've been trying to find a documentation, but I don't know where it is.

Thank you.

**Comment by lihuiknight** [comment]
ok, thanks. i close this issue.
