### ISSUE TITLE
truncation trick

### ISSUE THREAD

**Issue by lihuiknight** [POSTECH-CVLab/PyTorch-StudioGAN#62]
Dear author,

I am reading your implementation on latent sampling from `sample.py` (function: `sample_latents`).  For a gaussian sampling as implemented by `latents = torch.randn(batch_size, dim, device=device)/truncated_factor`. 

I notice that the above implementation is not a standard truncation trick, which is defined by 

`The Truncation Trick is a latent sampling procedure for generative adversarial networks, where we sample  from a truncated normal (where values which fall outside a range are resampled to fall inside that range)`

**Comment by MINGUKKANG** [comment]
Thank you very much.

I will reflect your reporting ASAP.

Best,

Minguk

**Comment by lihuiknight** [comment]
Let me know if you have fixed it.

**Comment by MINGUKKANG** [comment]
Hi,

Thank you so much.

I have corrected the wrong implementation of truncation trick. 

Please refer to "src/utils/sample.py" for more details.

**Comment by lihuiknight** [comment]
`values = truncnorm.rvs(-threshold, threshold, size=size)` is not defined as seen in [line](https://github.com/POSTECH-CVLab/PyTorch-StudioGAN/blob/master/src/utils/sample.py#L22) ?

**Comment by lihuiknight** [comment]
also, i think using `latents_eps = (1-perturb)*latents + perturb*sample_normal(batch_size, dim, -1.0, device)` in [line ](https://github.com/POSTECH-CVLab/PyTorch-StudioGAN/blob/6c696f60b6fac6e2af9f8e929e9e694ba4be5b65/src/utils/sample.py#L63) should be more reasonable, because such definition maintains a realistic distribution, whose cumulative distribution function is 1.

What do you think?

**Comment by MINGUKKANG** [comment]
Hi,

Thank you for your suggestion.

I think that the method you suggested is reasonable. 

However, I already conducted BigGAN-Mod/ContraGAN + ICR experiments using the "latents + pertub*sample_normal" way. 

We have also decided to keep StudioGAN code in its current state in order to exactly implement the original ICR regularization.

Nice suggestion and thank you.

Best, 

Minguk

**Comment by lihuiknight** [comment]
Yes. I see. The experimental results on large-scale image datasets are very expensive.

**Comment by MTandHJ** [comment]
Hi,

It seems that the truncated_normal returns a ndarray rather than a tensor.

**Comment by lihuiknight** [comment]
@MTandHJ I report the similar bug, as seen [here](https://github.com/POSTECH-CVLab/PyTorch-StudioGAN/issues/63#issuecomment-817666955)

**Comment by MINGUKKANG** [comment]
Thank you.

I have fixed the problem above.

Best,

Minguk

**Comment by lihuiknight** [comment]
@MINGUKKANG this function may want to return `latents_eps` ? see details in this [line](https://github.com/POSTECH-CVLab/PyTorch-StudioGAN/blob/6c696f60b6fac6e2af9f8e929e9e694ba4be5b65/src/utils/sample.py#L77).
