### ISSUE TITLE
little confusing about change_generator_mode

### ISSUE THREAD

**Issue by lihuiknight** [POSTECH-CVLab/PyTorch-StudioGAN#66]
Dear author,

I am reading your implementation. I'm little confusing about the function `change_generator_mode` in [line](https://github.com/POSTECH-CVLab/PyTorch-StudioGAN/blob/66309a7c1c0f649e9bf089303d08e04aefff1431/src/utils/misc.py#L362).
Especially for this [line](https://github.com/POSTECH-CVLab/PyTorch-StudioGAN/blob/66309a7c1c0f649e9bf089303d08e04aefff1431/src/utils/misc.py#L378): `apply_accumulate_stat(gen_tmp, standing_step, prior, batch_size, z_dim, num_classes, device)`.

Thanks.
Ken

**Comment by MINGUKKANG** [comment]
Hi,

Please refer to BigGAN paper, especially the standing statistics part in Appendix.

This function is a implementation of the standing statistics trick.

Thank you.

Best,

Minguk

**Comment by lihuiknight** [comment]
thanks a lot.

**Comment by Nayan-chereddycmd** [comment]
Stopppp
