### ISSUE TITLE
Using my own dataset.

### ISSUE THREAD

**Issue by vsantjr** [POSTECH-CVLab/PyTorch-StudioGAN#69]
Hello,

Congratulations for this contribution. I am trying to use StudioGAN but I am wondering on how to use my own dataset to generate the images and not to rely on the standard datasets (CIFAR10, ...).

Thanks.

**Comment by MINGUKKANG** [comment]
Hello, 

Yes, you can.

What you need to do is just to change config.json file!

If I want to train BigGAN on CUB200 dataset, I should change a config.json as follows:

```

{
  "data_processing":{ 
    "dataset_name": "CUB200",
    "data_path": "./data/CUB200",
    "img_size": 128,
    "num_classes": 200,
    "batch_size4prcsing": 256,
    "chunk_size": 500,
    "compression": false
  },
...
      "z_dim": z  \in [80 (for 32 resolution), 100 (for 64 resolution), 120 (for 128 resolution],
...
}
```

**Comment by vsantjr** [comment]
Thank you Minguk. 

I will try it.
