### ISSUE TITLE
Is that clear that its not able to evaluate on custom dataset?

### ISSUE THREAD

**Issue by crankyz** [POSTECH-CVLab/PyTorch-StudioGAN#72]
CUDA_VISIBLE_DEVICES=0,...,N python src/main.py -fa -std_stat --standing_step 200000 -c src/configs/ILSVRC2012/BigGAN256.json --checkpoint_folder checkpoints --log_output_path src.log
src/main.py:106: UserWarning: You have chosen a specific GPU. This will completely disable data parallelism.
  warnings.warn('You have chosen a specific GPU. This will completely disable data parallelism.')
Traceback (most recent call last):
  File "src/main.py", line 120, in <module>
    main()
  File "src/main.py", line 110, in main
    check_flags(train_configs, model_configs, world_size)
  File "/home/igor/PyTorch-StudioGAN/src/utils/misc.py", line 229, in check_flags
    "StudioGAN dose not support the evalutation protocol that uses the test dataset on imagenet, tiny imagenet, and custom datasets"
AssertionError: StudioGAN dose not support the evalutation protocol that uses the test dataset on imagenet, tiny imagenet, and custom datasets

Or it will work if I train on my dataset?

**Comment by MINGUKKANG** [comment]
AssertionError: StudioGAN dose not support the evalutation protocol that uses the test dataset on imagenet, tiny imagenet, and custom datasets

Hi,

Ah, I forget to remove that assert error. 

Just remove, then you can evaluate your model using valid/test moments for FID. 

Thank you.

**Comment by crankyz** [comment]
Ok, will try. Thank you for fast answer.
