### ISSUE TITLE
How to generate images?

### ISSUE THREAD

**Issue by ChristofJugel** [POSTECH-CVLab/PyTorch-StudioGAN#75]
Hello :)

Am I missing the function that generates images, after the model training is completed?
If not, how do I approach it best?

**Comment by MINGUKKANG** [comment]
Hi,

I am sorry for the late reply. 

You can generate images from the pre-trained checkpoint using -iv (generate image canvas) or -s (generate 50k images). 

Please refer to the blow screenshot.

<img width="858" alt="image" src="https://user-images.githubusercontent.com/30516904/126026119-c2ae5a7f-ef15-49f8-aee2-54e753d5e355.png">

Thank you.

Minguk
