### ISSUE TITLE
How can I get the same result as you?

### ISSUE THREAD

**Issue by DylanTao94** [POSTECH-CVLab/PyTorch-StudioGAN#76]
Hi,

I run the ContraGAN on CIFAR10 using the config file you provided and without any modification. However, I got a worse result with 10.435 FID while your result is 8.065. I wonder what's the different between us. In addition, you get a much better result than the figure reported in the paper(10.597±0.273), how did you do that?

If anyone faces the same issue, please tell me. Thank you!

**Comment by MINGUKKANG** [comment]
Hi,

Thank you for your bug reporting.

Do you train ContraGAN using two GPUs?

Also, I want to know the terminal command you used to train ContraGAN.

Thank you.

**Comment by DylanTao94** [comment]
Hi, 

The command I use is 
`!CUDA_VISIBLE_DEVICES=0 python3 src/main.py -t -e -c /content/PyTorch-StudioGAN/src/configs/CIFAR10/ContraGAN.json`

I run it on Colab with one GPU(Tesla P100-PCIE-16GB)

**Comment by MINGUKKANG** [comment]
please add --eval_type "test" --stat_otf on your command.

**Comment by DylanTao94** [comment]
Thank you very much!

**Comment by MINGUKKANG** [comment]
you can evaluate a pre-trained model using 
```
CUDA_VISIBLE_DEVICES=0 python3 src/main.py -t -e -c /content/PyTorch-StudioGAN/src/configs/CIFAR10/ContraGAN.json --eval_type "test" --stat_otf --checkpoint_folder "CHECKPOINT_FOLDER"
.

**Comment by DylanTao94** [comment]
Great, I'll try.
