### ISSUE TITLE
RUN THE CODE

### ISSUE THREAD

**Issue by wwjwy** [POSTECH-CVLab/PyTorch-StudioGAN#80]
has anyone run the code successfully?  i cannot set the right environment

**Comment by MINGUKKANG** [comment]
Hi, Thank you for your interest in our work.

Since StudioGAN was released, there have been many updates. Thus, it seems that the enviroment.yaml file needs to be updated. I will update the file ASAP (~48 hours).

BTW, what graphics card are you using? You need to install proper PyTorch version depends on the type of graphic card.

Thank you.

**Comment by wwjwy** [comment]
![IMG_7790(20210908-152427)](https://user-images.githubusercontent.com/66406998/132465058-0fa6fa84-7ae3-4fc1-95b9-ebc72e30b8fe.JPG)
i use pytorch1.6

**Comment by wwjwy** [comment]
the problem is shown in the picture

**Comment by MINGUKKANG** [comment]
Can you explain your situation more specifically?

**Comment by wwjwy** [comment]
When I configured the environment according to requirements.md, I found that torchlars could not be installed. When I run the code, there will be a problem as shown in the figure. I think the problem may be that the code contains C++ language.

**Comment by MINGUKKANG** [comment]
Just remove torchlars in environment.yaml, remove the line "from torchlars import LARS" in loader.py, and reinstall all library. It will resolve the problem.

**Comment by binkiebinkie** [comment]
I ran into the same issue, and just to document what happened it's that torchlars doesn't support Windows. I am trying to get the environment working on a windows machine

**Comment by MINGUKKANG** [comment]
We removed the torchlars module in StudioGAN since the module is no longer used in our library.

Thank you.
