### ISSUE TITLE
Running on Windows 10

### ISSUE THREAD

**Issue by binkiebinkie** [POSTECH-CVLab/PyTorch-StudioGAN#82]
Hello, 
Has anyone been able to get this environment running on Windows 10? I have almost gotten it running but I get the following issue when I try to run the command `set CUDA_VISIBLE_DEVICES=0 & py -3.7 src/main.py -t -e -c CONFIG_PATH` subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

![image](https://user-images.githubusercontent.com/48534322/133085429-3e6a86ef-ce1a-41fa-bec0-b8b755c285bc.png)

A couple of notes I found for getting it set up so far on Windows:
- using `conda env create -f environment.yml -n studiogan` doesn't work as the environment.yml file is for Linux (I think, that's what I read) so I ended up going through requirements.txt and installing everything with the command `py -3.7 -m pip install [package name]==[package version]` 
- Setting environment variables in Windows in script commands doesn't work like Linux, so we use the syntax `set CUDA_VISIBLE_DEVICES=0 &` instead in the command to run it

**Comment by MINGUKKANG** [comment]
Hi,

This is an error caused by the gcc library you installed.

If you do not plan to use adaptive discriminator augmentation (ADA) for data efficient GAN training, removing "from utils.ada import ADAugment" in ./src/worker.py (line 23) will resolve your problem. 

Thank you.

**Comment by binkiebinkie** [comment]
@MINGUKKANG it worked! Thanks so much for your quick reply, excited to work with this library

**Comment by binkiebinkie** [comment]
Oh, actually I have one more question. I am looking to train a model on photos like the following; bugs with white backgrounds. Do you have any recommendations on a method/model to use? Please and thank you!

![ladybug1](https://user-images.githubusercontent.com/48534322/133255474-116808ac-889f-40fa-8383-b6101218fd25.jpg)
![ladybug0](https://user-images.githubusercontent.com/48534322/133255475-75459289-fa69-4446-b55f-9beb548302d4.jpg)
![ladybug2](https://user-images.githubusercontent.com/48534322/133255476-677fffcf-66fd-411b-be5c-2d673f0dc92d.png)

**Comment by MINGUKKANG** [comment]
Hi,

I recommend using StyleGAN2 to train your GAN model.
(https://github.com/NVlabs/stylegan2-ada-pytorch)

StyleGAN2 is a good generator for synthesizing center-aligned images like AFHQ and FFHQ datasets.

Many GANs in StudioGAN are specialized in generating datasets whose inter-class and intra-class variations are large. 

Many GANs in StudioGAN library are specialized in generating datasets with large inter-class and intra-class variations.

Thank you.

**Comment by binkiebinkie** [comment]
Oh okay great, thank you for your guidance. Pretty new to this space. Thanks!
